require 'diff_match_patch'
require 'distinctio/version'
require 'distinctio/distinctio'
require 'distinctio/differs/base'
require 'distinctio/differs/object'
require 'distinctio/differs/simple'
require 'distinctio/differs/text'